# Generated by Django 2.2 on 2019-04-26 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('career', models.TextField()),
                ('creDt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
