# Generated by Django 2.2 on 2019-04-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamList',
            new_name='TeamListss',
        ),
    ]
