# Generated by Django 2.2 on 2019-04-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190430_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamListss',
            new_name='List',
        ),
    ]
