# Generated by Django 2.2 on 2019-07-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='after',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='before',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='otherTeamNm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('0101', '4-4-2'), ('0102', '3-5-2'), ('0103', '4-2-3-1'), ('0104', '4-3-3'), ('0105', '5-4-1'), ('0106', '4-5-1'), ('0200', '포메이션 변경'), ('0300', '선수 교체'), ('0400', '필드골'), ('0401', 'pk골'), ('0402', '프리킥골'), ('0403', '어시스트'), ('0404', '슈팅'), ('0405', '크로스'), ('0406', '헤더'), ('0407', '공간침투'), ('0408', '공간패스'), ('0409', '선방'), ('0500', '컨트롤미스'), ('0501', '패스미스'), ('0502', '체력저하'), ('0600', '파울'), ('0601', '옐로카드'), ('0602', '레드카드')], default='', max_length=4),
        ),
    ]
