# Generated by Django 2.2 on 2019-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.TextField()),
                ('height', models.DateTimeField(auto_now=True)),
                ('weight', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('speed', models.CharField(max_length=10)),
                ('creDt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
